version: '2'
services:
  angular:
    build: client
    image: cash-stash-client:1.0
    environment:
      - SERVER_URL=http://${DOCKER_HOST_IP}:${SERVER_PORT}/api/v1
      - NODE_ENV=${NODE_ENV}
    ports:
      - '8000:8000'
    depends_on:
      - express
    container_name: cash_client
  express:
    build: server
    image: cash-stash-server:1.0
    environment:
      - IP=${DOCKER_HOST_IP}
      - PORT=${SERVER_PORT}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - SECRET=${SECRET}
      - NODE_ENV=${NODE_ENV}
      - MONGO_URL=mongodb://mongo/cash-stash-development
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    container_name: cash_server
  mongo:
    image: mongo:${MONGO_VERSION}
    ports:
      - '27017:27017'
    container_name: cash_mongo
