swagger: '2.0'
info:
  title: CashStash API
  description: CashStash - Lightweight money tracking application.
  version: '1.0.0'
basePath: /api/v1/
produces:
  - application/json
paths:
  $ref: ./src/paths.yml
security:
  - apiKeyAuth: []
securityDefinitions:
  apiKeyAuth:
    type: apiKey
    in: header
    name: x-access-token
definitions:
  Response:
    type: object
    properties:
      message:
        type: string
      result:
        type: array
        items:
          format: object
